### ISSUE TITLE
Assigned To Heritage to childs

### ISSUE THREAD

**Issue by EdoTapia** [ostreifel/Links-Group#4]
Hello there, im using this extension a lot, i want to ask if it is possible to allow the inheritance of assigned to the children.
Currently when you add children to a work item they are left without user assignment the extension is very useful adding children and checking what is already complete, however you must be manually changing the assigned user, in our process we prefer that it be assigned to the same person responsible for the parent's work item.

Best regards!

**Comment by ostreifel** [comment]
Updated.
